sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - /.*/
before_install:
  - npm install -g @angular/cli 
  - npm install -g firebase-tools 
install:
  - npm install
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
